import 'package:flutter/material.dart';
import 'package:flutter_bloc/flutter_bloc.dart';

import '../../presentation/profile/cubit/locale_cubit.dart';

class AppLocalizations {
  static const Map<String, Map<String, String>> _translations = {
    'en': {
      // Profile
      'account_settings': 'Account Settings',
      'general': 'General',
      'my_orders': 'My Orders',
      'my_orders_sub': 'Track, return or buy things again',
      'shipping_addresses': 'Shipping Addresses',
      'shipping_addresses_sub': 'Manage your delivery locations',
      'payment_methods': 'Payment Methods',
      'payment_methods_sub': 'Visa, MasterCard, PayPal',
      'privacy_policy': 'Privacy Policy',
      'terms_conditions': 'Terms & Conditions',
      'about_us': 'About Us',
      'language': 'Language',
      'language_sub': 'Choose your preferred language',
      'logout': 'Logout',
      'member': 'Member',
      'select_language': 'Select Language',
      'english': 'English',
      'arabic': 'العربية',
      // Home
      'welcome_back': 'Welcome back',
      'brands': 'Brands',
      'new_arrivals': 'New Arrivals',
      'recommended': 'Recommended',
      'see_more': 'See More',
      'categories': 'Categories',
      'blogs': 'Blogs',
      'blog_post': 'Blog post',
      'all_products': 'All Products',
      // Search
      'search_hint': 'Search products...',
      'recent_searches': 'Recent Searches',
      'suggestions': 'Suggestions',
      'no_history': 'No search history yet',
      'no_results': 'No results found',
      'try_another': 'Try a different search term',
      // Cart
      'my_cart': 'My Cart',
      'order_summary': 'Order Summary',
      'subtotal': 'Subtotal',
      'discount': 'Discount',
      'total': 'Total',
      'checkout': 'Checkout',
      'empty_cart': 'Your cart is empty',
      'empty_cart_sub': 'Browse products and add items to your cart',
      'item': 'item',
      'items': 'items',
      'you_save': 'You save',
      'clear_cart': 'Clear Cart',
      'clear_cart_ask': 'Are you sure you want to remove all items from your cart?',
      'cancel': 'Cancel',
      'clear': 'Clear',
      'removed': 'Removed',
      'undo': 'Undo',
      'added_to_cart': 'Added to Cart!',
      'checkout_offline': 'Checkout is not available offline',
      // Checkout & Shipping
      'shipping_info': 'Shipping Info',
      'shipping_address': 'Shipping Address',
      'edit': 'Edit',
      'no_address': 'No address available',
      'select_address': 'Select Address',
      'add_new_address': 'Add New Address',
      'shipping_method': 'Shipping Method',
      'standard': 'Standard',
      'express': 'Express',
      'store_pickup': 'Store Pickup',
      'free': 'Free',
      'days': 'days',
      'today': 'Today',
      'next': 'Next',
      'confirm_order': 'Confirm Order',
      'payment_method': 'Payment Method',
      'credit_card': 'Credit Card',
      'apple_pay': 'Apple Pay',
      'paypal': 'PayPal',
      'cash_on_delivery': 'Cash on Delivery',
      'visa_mastercard': 'Visa, Mastercard',
      'fast_secure': 'Fast & Secure',
      'direct_payment': 'Direct Payment',
      'pay_at_door': 'Pay at your door',
      // Order Confirmation
      'order_confirmed': 'Order Confirmed!',
      'order_number': 'Order Number',
      'order_success_msg':
          'has been placed successfully. We will notify you once it heads your way.',
      'continue_shopping': 'Continue Shopping',
      // Connectivity & Errors
      'offline_disconnected': 'You are now offline',
      'connection_restored': 'Connection restored',
      'no_internet_no_data': 'No internet connection and no cached data',
      'load_failed': 'Failed to load products',
      'no_internet': 'No internet connection',
      'categories_load_failed': 'Failed to load categories',
      'retry': 'Retry',
      'load_more_failed': 'Failed to load more items',
      'reviews': 'reviews',
      'description': 'Description',
      'ingredients': 'Ingredients',
      'how_to_use': 'How to use',
      'related_products': 'Products you may also like',
      'add_to_cart': 'Add to Cart',
      'out_of_stock': 'Out of Stock',
      'free_delivery': 'Free Delivery',
      'nearest_store': 'Available in the nearest store',
      'limited_edition': 'Limited Edition',
      'out_of_stock_msg': 'Out of stock, will be available soon',
      'buy_now': 'Buy now',
      'offline_msg': 'Please check your connection and try again',
      'try_again': 'Try Again',
      'load_error': 'An error occurred while loading data',
      'reached_end': 'You have reached the end',
    },
    'ar': {
      // Profile
      'account_settings': 'إعدادات الحساب',
      'general': 'عام',
      'my_orders': 'طلباتي',
      'my_orders_sub': 'تتبع، إرجاع أو شراء مرة أخرى',
      'shipping_addresses': 'عناوين الشحن',
      'shipping_addresses_sub': 'إدارة مواقع التسليم',
      'payment_methods': 'طرق الدفع',
      'payment_methods_sub': 'فيزا، ماستركارد، باي بال',
      'privacy_policy': 'سياسة الخصوصية',
      'terms_conditions': 'الشروط والأحكام',
      'about_us': 'من نحن',
      'language': 'اللغة',
      'language_sub': 'اختر لغتك المفضلة',
      'logout': 'تسجيل الخروج',
      'member': 'عضو',
      'select_language': 'اختر اللغة',
      'english': 'English',
      'arabic': 'العربية',
      // Home
      'welcome_back': 'أهلاً بك من جديد',
      'brands': 'الماركات',
      'new_arrivals': 'أحدث المنتجات',
      'recommended': 'مقترح لك',
      'see_more': 'عرض الكل',
      'categories': 'الأقسام',
      'blogs': 'المدونات',
      'blog_post': 'منشور مدونة',
      'all_products': 'جميع المنتجات',
      // Search
      'search_hint': 'ابحث عن المنتجات...',
      'recent_searches': 'عمليات البحث الأخيرة',
      'suggestions': 'اقتراحات',
      'no_history': 'لا يوجد سجل بحث',
      'no_results': 'لا توجد نتائج',
      'try_another': 'جرب كلمة بحث أخرى',
      // Cart
      'my_cart': 'سلة التسوق',
      'order_summary': 'ملخص الطلب',
      'subtotal': 'المجموع الفرعي',
      'discount': 'الخصم',
      'total': 'المجموع الكلي',
      'checkout': 'الدفع',
      'empty_cart': 'السلة فارغة',
      'empty_cart_sub': 'تصفح المنتجات وأضف ما ينقصك إلى السلة',
      'item': 'منتج',
      'items': 'منتجات',
      'you_save': 'لقد وفرت',
      'clear_cart': 'مسح السلة',
      'clear_cart_ask': 'هل أنت متأكد من حذف جميع المنتجات من السلة؟',
      'cancel': 'إلغاء',
      'clear': 'مسح',
      'removed': 'تم حذف',
      'undo': 'تراجع',
      'added_to_cart': 'تمت الإضافة للسلة!',
      'checkout_offline': 'الدفع غير متاح في وضع عدم الاتصال',
      // Checkout & Shipping
      'shipping_info': 'معلومات الشحن',
      'shipping_address': 'عنوان الشحن',
      'edit': 'تعديل',
      'no_address': 'لا يوجد عنوان متاح',
      'select_address': 'اختر العنوان',
      'add_new_address': 'إضافة عنوان جديد',
      'shipping_method': 'طريقة الشحن',
      'standard': 'عادي',
      'express': 'سريع',
      'store_pickup': 'استلام من المتجر',
      'free': 'مجاناً',
      'days': 'أيام',
      'today': 'اليوم',
      'next': 'التالي',
      'confirm_order': 'تأكيد الطلب',
      'payment_method': 'طريقة الدفع',
      'credit_card': 'بطاقة ائتمان',
      'apple_pay': 'Apple Pay',
      'paypal': 'PayPal',
      'cash_on_delivery': 'الدفع عند الاستلام',
      'visa_mastercard': 'فيزا، ماستركارد',
      'fast_secure': 'سريع وآمن',
      'direct_payment': 'دفع مباشر',
      'pay_at_door': 'ادفع عند الباب',
      // Order Confirmation
      'order_confirmed': 'تم تأكيد طلبك!',
      'order_number': 'رقم الطلب',
      'order_success_msg': 'بنجاح. سنقوم بإشعارك فور خروجه للتوصيل.',
      'continue_shopping': 'متابعة التسوق',
      // Connectivity & Errors
      'offline_disconnected': 'تم قطع الاتصال بالإنترنت – أنت الآن في وضع عدم الاتصال',
      'connection_restored': 'تم استعادة الاتصال بالإنترنت',
      'no_internet_no_data': 'لا يوجد اتصال بالإنترنت ولا توجد بيانات مخزنة',
      'load_failed': 'فشل تحميل المنتجات',
      'no_internet': 'لا يوجد اتصال بالإنترنت',
      'categories_load_failed': 'تعذر جلب التصنيفات',
      'retry': 'إعادة المحاولة',
      'load_more_failed': 'فشل تحميل المزيد',
      'reviews': 'تقييم',
      'description': 'الوصف',
      'ingredients': 'المكونات',
      'how_to_use': 'طريقة الاستخدام',
      'related_products': 'منتجات قد تعجبك أيضاً',
      'add_to_cart': 'أضف للسلة',
      'out_of_stock': 'نفذت الكمية',
      'free_delivery': 'توصيل مجاني',
      'nearest_store': 'متوفر في أقرب متجر',
      'limited_edition': 'إصدار محدود',
      'out_of_stock_msg': 'غير متوفر في المخزون، سيتوفر مجدداً قريباً',
      'buy_now': 'اشتري الآن',
      'offline_msg': 'يرجى التحقق من الاتصال والمحاولة مرة أخرى',
      'try_again': 'حاول مرة أخرى',
      'load_error': 'حدث خطأ أثناء تحميل البيانات',
      'reached_end': 'لقد وصلت إلى النهاية',
    },
  };

  static String tr(String key, String locale) {
    return _translations[locale]?[key] ?? _translations['en']?[key] ?? key;
  }
}

extension BuildContextTranslationExtension on BuildContext {
  String tr(String key) {
    final lang = watch<LocaleCubit>().state.languageCode;
    return AppLocalizations.tr(key, lang);
  }

  String trRead(String key) {
    final lang = read<LocaleCubit>().state.languageCode;
    return AppLocalizations.tr(key, lang);
  }
}
